/**
 * Temporal Workflow Fix Routes for Workflow Automation Service
 * Handles determinism fixes and workflow optimization
 */

import { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';
import { promises as fs } from 'fs';
import path from 'path';
import { createServiceLogger } from '../shared-utils-local';

const logger = createServiceLogger('temporal-fix-routes');

interface TemporalFixRequest {
  workflowFiles: string[];
  determinismIssues: string[];
  targetPath: string;
}

export async function temporalFixRoutes(fastify: FastifyInstance): Promise<void> {
  
  // Fix Temporal determinism violations
  fastify.post<{ Body: TemporalFixRequest }>('/api/temporal/fix-determinism', {
    schema: {
      body: {
        type: 'object',
        required: ['workflowFiles', 'determinismIssues', 'targetPath'],
        properties: {
          workflowFiles: { 
            type: 'array',
            items: { type: 'string' }
          },
          determinismIssues: { 
            type: 'array',
            items: { type: 'string' }
          },
          targetPath: { type: 'string' }
        }
      },
      response: {
        200: {
          type: 'object',
          properties: {
            success: { type: 'boolean' },
            fixedFiles: { type: 'array', items: { type: 'string' } },
            workflowDefinitions: { type: 'object' },
            determinismCompliant: { type: 'boolean' }
          }
        }
      }
    }
  }, async (request: FastifyRequest<{ Body: TemporalFixRequest }>, reply: FastifyReply) => {
    const { workflowFiles, determinismIssues, targetPath } = request.body;
    
    logger.info('Processing Temporal determinism fixes', { 
      fileCount: workflowFiles.length,
      issueCount: determinismIssues.length,
      targetPath 
    });

    try {
      // Use LLM service to generate determinism-compliant workflows
      const llmService = fastify.llmService;
      
      const fixPrompt = `
        Fix the following Temporal workflow determinism violations:
        
        Issues: ${determinismIssues.join(', ')}
        
        Requirements:
        1. Replace direct activity imports with type-only imports
        2. Use proxyActivities with proper type definitions
        3. Ensure workflows only import @temporalio/workflow modules
        4. Maintain separation between workflow and activity code
        5. Keep existing functionality intact
        
        Generate TypeScript workflow files that are fully deterministic and Temporal-compliant.
        
        Workflow 1: Add Numbers Workflow
        - Accept two numbers as input
        - Add them using an activity
        - Cache result in Redis using an activity
        - Publish result to Redis channel using an activity
        - Return success result with sum
        
        Workflow 2: Divide Number Workflow  
        - Accept Redis channel as input
        - Receive number from Redis using an activity
        - Divide by 2 using an activity
        - Return success result with original number and result
        
        Use proper TypeScript types and maintain determinism.
      `;

      const llmResponse = await llmService.generateContent(fixPrompt);
      
      // Generate deterministic workflow files
      const addNumbersWorkflow = `/**
 * Add Numbers Workflow - Determinism Compliant
 * Generated by Workflow Automation Service
 */

import { proxyActivities } from '@temporalio/workflow';

// Type-only imports for activities
type AddNumbersActivity = (params: { num1: number, num2: number }) => Promise<number>;
type CacheAdditionResultActivity = (params: { cacheKey: string, sum: number }) => Promise<boolean>;
type PublishAdditionEventActivity = (params: { channel: string, payload: any }) => Promise<boolean>;

const { addNumbers, cacheAdditionResult, publishAdditionEvent } = proxyActivities<{
  addNumbers: AddNumbersActivity;
  cacheAdditionResult: CacheAdditionResultActivity;
  publishAdditionEvent: PublishAdditionEventActivity;
}>({
  startToCloseTimeout: '5 minutes',
  retry: {
    initialInterval: '1s',
    maximumAttempts: 3,
    backoffCoefficient: 2,
  },
});

export interface AddNumbersInput {
  num1: number;
  num2: number;
}

export interface AddNumbersResult {
  success: boolean;
  sum: number;
  workflow: string;
  timestamp: number;
}

export async function addNumbersWorkflow(input: AddNumbersInput): Promise<AddNumbersResult> {
  try {
    // Add the two numbers
    const sum = await addNumbers({ num1: input.num1, num2: input.num2 });
    
    // Cache the result in Redis
    const cacheKey = \`addition:\${input.num1}+\${input.num2}\`;
    await cacheAdditionResult({ cacheKey, sum });
    
    // Publish result to Redis for consumption by divide workflow
    await publishAdditionEvent({
      channel: 'addition:events',
      payload: {
        sum,
        originalNumbers: { num1: input.num1, num2: input.num2 },
        timestamp: Date.now()
      }
    });
    
    return {
      success: true,
      sum,
      workflow: 'add-numbers-workflow',
      timestamp: Date.now()
    };
  } catch (error) {
    throw new Error(\`Add numbers workflow failed: \${error instanceof Error ? error.message : String(error)}\`);
  }
}
`;

      const divideNumberWorkflow = `/**
 * Divide Number Workflow - Determinism Compliant
 * Generated by Workflow Automation Service
 */

import { proxyActivities } from '@temporalio/workflow';

// Type-only imports for activities
type ReceiveNumberFromRedisActivity = (channel: string) => Promise<number>;
type DivideByTwoActivity = (number: number) => Promise<number>;

const { receiveNumberFromRedis, divideByTwo } = proxyActivities<{
  receiveNumberFromRedis: ReceiveNumberFromRedisActivity;
  divideByTwo: DivideByTwoActivity;
}>({
  startToCloseTimeout: '5 minutes',
  retry: {
    initialInterval: '2s',
    maximumAttempts: 3,
    backoffCoefficient: 2,
  },
});

export interface DivideNumberInput {
  channel: string;
}

export interface DivideNumberResult {
  success: boolean;
  originalNumber: number;
  result: number;
  workflow: string;
  timestamp: number;
}

export async function divideNumberWorkflow(input: DivideNumberInput): Promise<DivideNumberResult> {
  try {
    // Receive number from Redis channel
    const originalNumber = await receiveNumberFromRedis(input.channel || 'addition:events');
    
    // Divide the number by 2
    const result = await divideByTwo(originalNumber);
    
    return {
      success: true,
      originalNumber,
      result,
      workflow: 'divide-number-workflow',
      timestamp: Date.now()
    };
  } catch (error) {
    throw new Error(\`Divide number workflow failed: \${error instanceof Error ? error.message : String(error)}\`);
  }
}
`;

      // Write the fixed workflow files
      const addWorkflowPath = path.join(targetPath, 'src/workflows/add-numbers-workflow.ts');
      const divideWorkflowPath = path.join(targetPath, 'src/workflows/divide-number-workflow.ts');
      
      await fs.writeFile(addWorkflowPath, addNumbersWorkflow, 'utf-8');
      await fs.writeFile(divideWorkflowPath, divideNumberWorkflow, 'utf-8');
      
      logger.info('Successfully fixed Temporal determinism violations', {
        addWorkflowPath,
        divideWorkflowPath
      });

      return reply.code(200).send({
        success: true,
        fixedFiles: [addWorkflowPath, divideWorkflowPath],
        workflowDefinitions: {
          addNumbersWorkflow: 'add-numbers-workflow',
          divideNumberWorkflow: 'divide-number-workflow'
        },
        determinismCompliant: true
      });

    } catch (error) {
      logger.error(error as Error, 'Failed to fix Temporal determinism violations');
      return reply.code(500).send({
        success: false,
        error: 'Failed to fix determinism violations',
        details: (error as Error).message
      });
    }
  });
}