/**
 * Sample Workflow Generator
 * Creates realistic workflow code that can be executed in Temporal
 */

export class SampleWorkflowGenerator {
  
  /**
   * Generate e-commerce order processing workflow
   */
  static generateECommerceWorkflow(): string {
    return `/**
 * E-Commerce Order Processing Workflow
 * Generated by AI with iterative improvements
 */

import { log } from '@temporalio/workflow';

export async function ECommerceOrderWorkflow(orderData: {
  orderId: string;
  customerId: string;
  items: Array<{ productId: string; quantity: number; price: number }>;
  paymentMethod: string;
  shippingAddress: any;
}): Promise<any> {
  
  log.info('Starting e-commerce order processing', { orderId: orderData.orderId });

  try {
    // Step 1: Validate order data
    log.info('Validating order data', { orderId: orderData.orderId });
    const isValid = await validateInput(orderData);
    
    if (!isValid) {
      throw new Error('Invalid order data provided');
    }

    // Step 2: Check inventory availability
    log.info('Checking inventory availability', { orderId: orderData.orderId });
    const inventoryResult = await checkInventory(orderData.items);
    
    if (!inventoryResult.available) {
      throw new Error('Insufficient inventory for order');
    }

    // Step 3: Process payment
    log.info('Processing payment', { orderId: orderData.orderId });
    const paymentResult = await processPayment({
      amount: orderData.items.reduce((sum, item) => sum + (item.price * item.quantity), 0),
      paymentMethod: orderData.paymentMethod,
      orderId: orderData.orderId
    });

    if (!paymentResult.success) {
      throw new Error('Payment processing failed');
    }

    // Step 4: Create shipment
    log.info('Creating shipment', { orderId: orderData.orderId });
    const shipmentResult = await createShipment({
      orderId: orderData.orderId,
      items: orderData.items,
      address: orderData.shippingAddress,
      reservationId: inventoryResult.reservationId
    });

    // Step 5: Send confirmation notifications
    log.info('Sending order confirmation', { orderId: orderData.orderId });
    await sendNotification({
      type: 'order_confirmation',
      customerId: orderData.customerId,
      orderId: orderData.orderId,
      trackingNumber: shipmentResult.trackingNumber
    });

    // Step 6: Log completion event
    await logEvent({
      type: 'order_completed',
      orderId: orderData.orderId,
      timestamp: Date.now(),
      transactionId: paymentResult.transactionId,
      shipmentId: shipmentResult.shipmentId
    });

    const result = {
      success: true,
      orderId: orderData.orderId,
      transactionId: paymentResult.transactionId,
      shipmentId: shipmentResult.shipmentId,
      trackingNumber: shipmentResult.trackingNumber,
      status: 'completed',
      processedAt: new Date().toISOString()
    };

    log.info('E-commerce order processing completed successfully', result);
    return result;

  } catch (error) {
    log.error('E-commerce order processing failed', { 
      orderId: orderData.orderId, 
      error: error.message 
    });

    // Send failure notification
    await sendNotification({
      type: 'order_failed',
      customerId: orderData.customerId,
      orderId: orderData.orderId,
      error: error.message
    });

    // Log failure event
    await logEvent({
      type: 'order_failed',
      orderId: orderData.orderId,
      error: error.message,
      timestamp: Date.now()
    });

    throw error;
  }
}`;
  }

  /**
   * Generate data processing workflow
   */
  static generateDataProcessingWorkflow(): string {
    return `/**
 * Data Processing Pipeline Workflow
 * Generated by AI with iterative improvements
 */

import { log } from '@temporalio/workflow';

export async function DataProcessingWorkflow(input: {
  dataSourceId: string;
  processingType: 'batch' | 'stream';
  outputFormat: string;
  qualityChecks: boolean;
}): Promise<any> {

  log.info('Starting data processing pipeline', { dataSourceId: input.dataSourceId });

  try {
    // Step 1: Validate input parameters
    log.info('Validating processing parameters', { dataSourceId: input.dataSourceId });
    const isValid = await validateInput(input);
    
    if (!isValid) {
      throw new Error('Invalid processing parameters');
    }

    // Step 2: Process the data
    log.info('Processing data', { 
      dataSourceId: input.dataSourceId, 
      type: input.processingType 
    });
    
    const processingResult = await processData(JSON.stringify({
      sourceId: input.dataSourceId,
      type: input.processingType,
      timestamp: Date.now()
    }));

    // Step 3: Quality checks (if enabled)
    if (input.qualityChecks) {
      log.info('Running quality checks', { dataSourceId: input.dataSourceId });
      const qualityValid = await validateInput({ 
        data: processingResult, 
        checks: ['completeness', 'accuracy'] 
      });
      
      if (!qualityValid) {
        throw new Error('Data quality checks failed');
      }
    }

    // Step 4: Send completion notification
    await sendNotification({
      type: 'data_processing_complete',
      dataSourceId: input.dataSourceId,
      result: 'success',
      recordsProcessed: 150000 // Simulated
    });

    // Step 5: Log completion
    await logEvent({
      type: 'data_processing_completed',
      dataSourceId: input.dataSourceId,
      processingType: input.processingType,
      timestamp: Date.now(),
      result: processingResult
    });

    const result = {
      success: true,
      dataSourceId: input.dataSourceId,
      processingResult,
      qualityScore: 0.96,
      recordsProcessed: 150000,
      processedAt: new Date().toISOString()
    };

    log.info('Data processing completed successfully', result);
    return result;

  } catch (error) {
    log.error('Data processing failed', { 
      dataSourceId: input.dataSourceId, 
      error: error.message 
    });

    await sendNotification({
      type: 'data_processing_failed',
      dataSourceId: input.dataSourceId,
      error: error.message
    });

    await logEvent({
      type: 'data_processing_failed',
      dataSourceId: input.dataSourceId,
      error: error.message,
      timestamp: Date.now()
    });

    throw error;
  }
}`;
  }

  /**
   * Generate notification workflow
   */
  static generateNotificationWorkflow(): string {
    return `/**
 * Multi-Channel Notification Workflow
 * Generated by AI with iterative improvements
 */

import { log } from '@temporalio/workflow';

export async function NotificationWorkflow(notification: {
  recipientId: string;
  messageType: string;
  channels: string[];
  priority: 'low' | 'normal' | 'high' | 'urgent';
  content: any;
}): Promise<any> {

  log.info('Starting notification delivery', { 
    recipientId: notification.recipientId,
    messageType: notification.messageType 
  });

  try {
    // Step 1: Validate notification data
    log.info('Validating notification data', { recipientId: notification.recipientId });
    const isValid = await validateInput(notification);
    
    if (!isValid) {
      throw new Error('Invalid notification data');
    }

    const deliveryResults = [];

    // Step 2: Send notification through each channel
    for (const channel of notification.channels) {
      try {
        log.info('Sending notification via channel', { 
          channel: channel,
          recipientId: notification.recipientId 
        });
        
        const result = await sendNotification({
          ...notification,
          channel,
          attempt: 1
        });

        deliveryResults.push({
          channel,
          success: result.sent,
          messageId: result.messageId,
          timestamp: Date.now()
        });

      } catch (channelError) {
        log.warn('Notification failed for channel', { 
          channel: channel,
          recipientId: notification.recipientId,
          error: channelError.message 
        });

        // Try fallback for failed channel
        if (channel === 'email' && notification.channels.includes('sms')) {
          log.info('Attempting SMS fallback for failed email', { 
            recipientId: notification.recipientId 
          });
          
          try {
            const fallbackResult = await sendNotification({
              ...notification,
              channel: 'sms',
              attempt: 2,
              fallbackReason: 'email_failed'
            });

            deliveryResults.push({
              channel: 'sms_fallback',
              success: fallbackResult.sent,
              messageId: fallbackResult.messageId,
              timestamp: Date.now()
            });

          } catch (fallbackError) {
            deliveryResults.push({
              channel: 'sms_fallback',
              success: false,
              error: fallbackError.message,
              timestamp: Date.now()
            });
          }
        }
      }
    }

    // Step 3: Log delivery results
    await logEvent({
      type: 'notification_delivery_complete',
      recipientId: notification.recipientId,
      messageType: notification.messageType,
      deliveryResults,
      timestamp: Date.now()
    });

    const successfulDeliveries = deliveryResults.filter(r => r.success);
    const result = {
      success: successfulDeliveries.length > 0,
      recipientId: notification.recipientId,
      messageType: notification.messageType,
      deliveryResults,
      successfulChannels: successfulDeliveries.length,
      totalChannels: deliveryResults.length,
      deliveredAt: new Date().toISOString()
    };

    log.info('Notification delivery completed', result);
    return result;

  } catch (error) {
    log.error('Notification workflow failed', { 
      recipientId: notification.recipientId, 
      error: error.message 
    });

    await logEvent({
      type: 'notification_workflow_failed',
      recipientId: notification.recipientId,
      error: error.message,
      timestamp: Date.now()
    });

    throw error;
  }
}`;
  }

  /**
   * Get sample input for workflows
   */
  static getSampleInputs() {
    return {
      ecommerce: {
        orderId: 'order_' + Date.now(),
        customerId: 'customer_12345',
        items: [
          { productId: 'prod_123', quantity: 2, price: 29.99 },
          { productId: 'prod_456', quantity: 1, price: 49.99 }
        ],
        paymentMethod: 'credit_card',
        shippingAddress: {
          street: '123 Main St',
          city: 'San Francisco', 
          state: 'CA',
          zip: '94102'
        }
      },
      dataProcessing: {
        dataSourceId: 'source_' + Date.now(),
        processingType: 'batch' as 'batch' | 'stream',
        outputFormat: 'json',
        qualityChecks: true
      },
      notification: {
        recipientId: 'user_789',
        messageType: 'order_confirmation',
        channels: ['email', 'sms'],
        priority: 'normal' as 'low' | 'normal' | 'high' | 'urgent',
        content: {
          subject: 'Order Confirmed',
          message: 'Your order has been successfully processed'
        }
      }
    };
  }
}