/**
 * Real Workflow Generator - Creates actual Temporal workflows and activities
 * This generates real files that can be deployed and executed by Temporal workers
 */

import { promises as fs } from 'fs';
import { join } from 'path';
import { createServiceLogger } from './shared-utils-local';

const logger = createServiceLogger('real-workflow-generator');

export interface GeneratedActivity {
  name: string;
  description: string;
  code: string;
  inputs: Record<string, string>;
  outputs: Record<string, string>;
  qualityScore: number;
}

export interface GeneratedWorkflow {
  workflowId: string;
  name: string;
  description: string;
  activities: GeneratedActivity[];
  workflowCode: string;
}

/**
 * Generate real Circle Area calculation activities
 */
export function generateCircleAreaActivities(workflowId: string): GeneratedActivity[] {
  return [
    {
      name: 'validateRadiusActivity',
      description: 'Validates that radius is a positive number',
      code: `
import { Activity } from '@temporalio/activity';

export async function validateRadiusActivity(radius: number): Promise<{ valid: boolean; radius: number; error?: string }> {
  console.log(\`🔍 Validating radius: \${radius}\`);
  
  if (typeof radius !== 'number' || isNaN(radius)) {
    return { valid: false, radius, error: 'Radius must be a valid number' };
  }
  
  if (radius <= 0) {
    return { valid: false, radius, error: 'Radius must be positive' };
  }
  
  console.log(\`✅ Radius validation passed: \${radius}\`);
  return { valid: true, radius };
}
`,
      inputs: { radius: 'number' },
      outputs: { valid: 'boolean', radius: 'number', error: 'string' },
      qualityScore: 0.95
    },
    {
      name: 'calculateCircleAreaActivity',
      description: 'Calculates circle area using π × r²',
      code: `
import { Activity } from '@temporalio/activity';

export async function calculateCircleAreaActivity(radius: number): Promise<{
  radius: number;
  area: number;
  area_exact: number;
  formula: string;
  pi_value: number;
  calculation: string;
}> {
  console.log(\`🧮 Calculating circle area for radius: \${radius}\`);
  
  // THE REAL MATHEMATICAL CALCULATION
  const area_exact = Math.PI * radius * radius;
  const area = Math.round(area_exact * 1000000) / 1000000; // 6 decimal places
  
  const result = {
    radius,
    area,
    area_exact,
    formula: 'π × r²',
    pi_value: Math.PI,
    calculation: \`\${Math.PI} × \${radius}² = \${area_exact}\`
  };
  
  console.log(\`🎯 AREA CALCULATED: \${area} (exact: \${area_exact})\`);
  return result;
}
`,
      inputs: { radius: 'number' },
      outputs: { 
        radius: 'number', 
        area: 'number', 
        area_exact: 'number', 
        formula: 'string', 
        pi_value: 'number',
        calculation: 'string'
      },
      qualityScore: 0.98
    },
    {
      name: 'formatResultActivity',
      description: 'Formats calculation result for output',
      code: `
import { Activity } from '@temporalio/activity';

export async function formatResultActivity(calculationData: {
  radius: number;
  area: number;
  area_exact: number;
  formula: string;
  pi_value: number;
  calculation: string;
}): Promise<{
  success: boolean;
  input: { radius: number };
  output: { area: number };
  message: string;
  calculation_details: any;
  workflow_id: string;
  generated_by: string;
}> {
  console.log(\`📋 Formatting calculation result...\`);
  
  const result = {
    success: true,
    input: { radius: calculationData.radius },
    output: { area: calculationData.area },
    message: \`Circle with radius \${calculationData.radius} has area \${calculationData.area} square units\`,
    calculation_details: {
      formula: calculationData.formula,
      pi_value: calculationData.pi_value,
      calculation: calculationData.calculation,
      raw_area: calculationData.area_exact,
      formatted_area: calculationData.area
    },
    workflow_id: '${workflowId}',
    generated_by: 'Real Workflow Automation Service'
  };
  
  console.log(\`📊 FORMATTED: \${result.message}\`);
  return result;
}
`,
      inputs: { calculationData: 'object' },
      outputs: { 
        success: 'boolean',
        input: 'object', 
        output: 'object', 
        message: 'string', 
        calculation_details: 'object',
        workflow_id: 'string',
        generated_by: 'string'
      },
      qualityScore: 0.92
    }
  ];
}

/**
 * Generate real Circle Area workflow code
 */
export function generateCircleAreaWorkflow(workflowId: string, activities: GeneratedActivity[]): string {
  return `
/**
 * Generated Circle Area Calculation Workflow
 * Workflow ID: ${workflowId}
 * Generated by: Real Workflow Automation Service
 */

import { proxyActivities, log } from '@temporalio/workflow';
import { 
  validateRadiusActivity,
  calculateCircleAreaActivity, 
  formatResultActivity 
} from './activities/${workflowId}';

// Create activity proxies with timeout configurations
const { 
  validateRadiusActivity: validateRadius,
  calculateCircleAreaActivity: calculateCircleArea,
  formatResultActivity: formatResult 
} = proxyActivities({
  startToCloseTimeout: '2 minutes',
  retry: {
    initialInterval: '1s',
    backoffCoefficient: 2.0,
    maximumInterval: '30s',
    maximumAttempts: 3,
  },
});

/**
 * Circle Area Calculation Workflow
 * Calculates the area of a circle given a radius
 */
export async function ${workflowId}Workflow(input: { radius: number }): Promise<{
  success: boolean;
  input: { radius: number };
  output: { area: number };
  message: string;
  calculation_details: any;
  workflow_id: string;
  generated_by: string;
}> {
  log.info('🚀 Starting Circle Area Calculation Workflow', { workflowId: '${workflowId}', input });
  
  try {
    // Step 1: Validate radius input
    log.info('Step 1: Validating radius input');
    const validation = await validateRadius(input.radius);
    
    if (!validation.valid) {
      log.error('Radius validation failed', { error: validation.error });
      throw new Error(\`Radius validation failed: \${validation.error}\`);
    }
    
    // Step 2: Calculate circle area
    log.info('Step 2: Calculating circle area');
    const calculationResult = await calculateCircleArea(validation.radius);
    
    // Step 3: Format result
    log.info('Step 3: Formatting result');
    const finalResult = await formatResult(calculationResult);
    
    log.info('🎉 Circle Area Calculation Workflow completed successfully', { 
      workflowId: '${workflowId}',
      result: finalResult 
    });
    
    return finalResult;
    
  } catch (error) {
    log.error('Circle Area Calculation Workflow failed', { 
      workflowId: '${workflowId}',
      error: error instanceof Error ? error.message : String(error)
    });
    
    throw error;
  }
}
`;
}

/**
 * Generate activity file content
 */
export function generateActivityFile(workflowId: string, activities: GeneratedActivity[]): string {
  const activityExports = activities.map(activity => activity.code).join('\n\n');
  
  return `
/**
 * Generated Activities for Circle Area Calculation
 * Workflow ID: ${workflowId}
 * Generated by: Real Workflow Automation Service
 */

${activityExports}
`;
}

/**
 * Create real workflow and activity files
 */
export async function createRealWorkflowFiles(workflowId: string, outputDir: string): Promise<GeneratedWorkflow> {
  logger.info('Creating real workflow files', { workflowId, outputDir });
  
  try {
    // Generate activities
    const activities = generateCircleAreaActivities(workflowId);
    
    // Generate workflow code
    const workflowCode = generateCircleAreaWorkflow(workflowId, activities);
    
    // Generate activity file
    const activityCode = generateActivityFile(workflowId, activities);
    
    // Ensure output directories exist
    const workflowDir = join(outputDir, 'workflows');
    const activityDir = join(outputDir, 'activities');
    
    await fs.mkdir(workflowDir, { recursive: true });
    await fs.mkdir(activityDir, { recursive: true });
    
    // Write workflow file
    const workflowPath = join(workflowDir, `${workflowId}.ts`);
    await fs.writeFile(workflowPath, workflowCode, 'utf-8');
    
    // Write activity file
    const activityPath = join(activityDir, `${workflowId}.ts`);
    await fs.writeFile(activityPath, activityCode, 'utf-8');
    
    logger.info('Successfully created real workflow files', {
      workflowId,
      workflowPath,
      activityPath,
      activitiesCount: activities.length
    });
    
    return {
      workflowId,
      name: `${workflowId}Workflow`,
      description: 'Real Circle Area Calculation Workflow',
      activities,
      workflowCode
    };
    
  } catch (error) {
    logger.error(error instanceof Error ? error : new Error(String(error)), { workflowId }, 'Failed to create real workflow files');
    throw error;
  }
}

/**
 * Deploy workflow files to Temporal worker
 */
export async function deployToTemporalWorker(
  workflowId: string, 
  generated: GeneratedWorkflow,
  workerPath: string
): Promise<void> {
  logger.info('Deploying workflow to Temporal worker', { workflowId, workerPath });
  
  try {
    // Copy files to Temporal worker directory
    const workerWorkflowsDir = join(workerPath, 'src', 'workflows');
    const workerActivitiesDir = join(workerPath, 'src', 'activities');
    
    // Ensure directories exist
    await fs.mkdir(workerWorkflowsDir, { recursive: true });
    await fs.mkdir(workerActivitiesDir, { recursive: true });
    
    // Copy workflow file
    const workflowDestPath = join(workerWorkflowsDir, `${workflowId}.ts`);
    await fs.writeFile(workflowDestPath, generated.workflowCode, 'utf-8');
    
    // Copy activity file
    const activityCode = generateActivityFile(workflowId, generated.activities);
    const activityDestPath = join(workerActivitiesDir, `${workflowId}.ts`);
    await fs.writeFile(activityDestPath, activityCode, 'utf-8');
    
    // Update worker index files to include new workflow and activities
    await updateWorkerIndexFiles(workflowId, workerWorkflowsDir, workerActivitiesDir);
    
    logger.info('Successfully deployed workflow to Temporal worker', {
      workflowId,
      workflowPath: workflowDestPath,
      activityPath: activityDestPath
    });
    
  } catch (error) {
    logger.error(error instanceof Error ? error : new Error(String(error)), { workflowId }, 'Failed to deploy to Temporal worker');
    throw error;
  }
}

/**
 * Update worker index files to include new workflows and activities
 */
async function updateWorkerIndexFiles(
  workflowId: string,
  workflowsDir: string,
  activitiesDir: string
): Promise<void> {
  // Update workflows index
  const workflowIndexPath = join(workflowsDir, 'index.ts');
  let workflowIndexContent = '';
  
  try {
    workflowIndexContent = await fs.readFile(workflowIndexPath, 'utf-8');
  } catch {
    // File doesn't exist, create new one
    workflowIndexContent = '// Generated workflows index\n';
  }
  
  // Add export for new workflow
  const workflowExport = `export { ${workflowId}Workflow } from './${workflowId}';`;
  if (!workflowIndexContent.includes(workflowExport)) {
    workflowIndexContent += `\n${workflowExport}\n`;
    await fs.writeFile(workflowIndexPath, workflowIndexContent, 'utf-8');
  }
  
  // Update activities index
  const activityIndexPath = join(activitiesDir, 'index.ts');
  let activityIndexContent = '';
  
  try {
    activityIndexContent = await fs.readFile(activityIndexPath, 'utf-8');
  } catch {
    // File doesn't exist, create new one
    activityIndexContent = '// Generated activities index\n';
  }
  
  // Add exports for new activities
  const activityExports = `export { validateRadiusActivity, calculateCircleAreaActivity, formatResultActivity } from './${workflowId}';`;
  if (!activityIndexContent.includes(activityExports)) {
    activityIndexContent += `\n${activityExports}\n`;
    await fs.writeFile(activityIndexPath, activityIndexContent, 'utf-8');
  }
}