/**
 * Standalone Workflow Automation Service
 * Simple version without complex dependencies
 */

import fastify from 'fastify';

const app = fastify({
  logger: {
    level: 'info'
  }
});

// Simple health check
app.get('/health', async (request, reply) => {
  return { 
    status: 'healthy', 
    service: 'workflow-automation',
    timestamp: new Date().toISOString()
  };
});

// Simple workflow generation endpoint
app.post('/api/workflows/generate', async (request, reply) => {
  const body = request.body as any;
  
  console.log('🔥 WORKFLOW AUTOMATION SERVICE: Generating workflow for:', body.name);
  
  // Generate TypeScript workflow files for circle area calculation
  const workflowCode = `/**
 * ${body.name} - Generated by Workflow Automation Service
 * ${body.description}
 */

import { proxyActivities, log } from '@temporalio/workflow';
import type * as activities from './activities';

const { 
  validateRadius, 
  calculateArea, 
  calculateCircumference, 
  calculateDiameter, 
  logGeometryCalculation 
} = proxyActivities<typeof activities>({
  startToCloseTimeout: '1 minute',
});

export async function ${body.name}(input: { radius: number }) {
  const workflowId = \`circle-area-\${Date.now()}\`;
  log.info('${body.name} started - REAL EXECUTION', { workflowId, input });
  
  try {
    // Step 1: Validate radius
    log.info('Step 1: Validating radius', { radius: input.radius });
    await validateRadius(input.radius);
    log.info('Radius validation completed successfully');

    // Step 2: Calculate area using π * radius²
    log.info('Step 2: Calculating area', { radius: input.radius });
    const area = await calculateArea(input.radius);
    log.info('Area calculation completed', { area });

    // Step 3: Calculate circumference as bonus
    log.info('Step 3: Calculating circumference', { radius: input.radius });
    const circumference = await calculateCircumference(input.radius);
    log.info('Circumference calculation completed', { circumference });

    // Step 4: Calculate diameter
    log.info('Step 4: Calculating diameter', { radius: input.radius });
    const diameter = await calculateDiameter(input.radius);
    log.info('Diameter calculation completed', { diameter });

    // Step 5: Log complete results
    log.info('Step 5: Logging geometry calculation');
    await logGeometryCalculation(input.radius, area, circumference, diameter);
    log.info('Geometry logging completed');
    
    const result = {
      success: true,
      input: input,
      area: area,
      circumference: circumference,
      diameter: diameter,
      operation: 'circle_geometry',
      workflowId: workflowId,
      completedAt: new Date().toISOString(),
      message: \`Successfully calculated circle geometry for radius \${input.radius}\`,
      formulas: {
        area: 'π × radius²',
        circumference: '2 × π × radius', 
        diameter: '2 × radius'
      }
    };

    log.info('${body.name} completed successfully', { response: result });
    return result;
    
  } catch (error) {
    log.error('${body.name} failed', { error: error.message, input });
    throw new Error(\`Circle area calculation failed: \${error.message}\`);
  }
}`;

  const activitiesCode = `/**
 * Real Activities for Circle Area Calculation Workflow
 * These execute actual geometry calculations on Temporal workers
 */

/**
 * Validates that the radius is a positive number
 */
export async function validateRadius(radius: number): Promise<void> {
  console.log('🔍 REAL ACTIVITY: Validating radius:', { radius });
  
  if (typeof radius !== 'number') {
    throw new Error('Radius must be a number');
  }
  
  if (isNaN(radius)) {
    throw new Error('Radius must be a valid number (not NaN)');
  }
  
  if (!isFinite(radius)) {
    throw new Error('Radius must be finite');
  }
  
  if (radius <= 0) {
    throw new Error('Radius must be positive (greater than 0)');
  }
  
  console.log('✅ REAL ACTIVITY: Radius validation successful');
}

/**
 * Calculates the area of a circle using π * radius²
 */
export async function calculateArea(radius: number): Promise<number> {
  console.log('📐 REAL ACTIVITY: Calculating area for radius:', radius);
  
  // Simulate processing time
  await new Promise(resolve => setTimeout(resolve, 100));
  
  const area = Math.PI * radius * radius;
  
  console.log('✅ REAL ACTIVITY: Area calculation completed:', \`π × \${radius}² = \${area}\`);
  return area;
}

/**
 * Calculates the circumference of a circle using 2 * π * radius
 */
export async function calculateCircumference(radius: number): Promise<number> {
  console.log('🔄 REAL ACTIVITY: Calculating circumference for radius:', radius);
  
  await new Promise(resolve => setTimeout(resolve, 80));
  
  const circumference = 2 * Math.PI * radius;
  
  console.log('✅ REAL ACTIVITY: Circumference calculation completed:', \`2 × π × \${radius} = \${circumference}\`);
  return circumference;
}

/**
 * Calculates the diameter of a circle using 2 * radius
 */
export async function calculateDiameter(radius: number): Promise<number> {
  console.log('📏 REAL ACTIVITY: Calculating diameter for radius:', radius);
  
  await new Promise(resolve => setTimeout(resolve, 50));
  
  const diameter = 2 * radius;
  
  console.log('✅ REAL ACTIVITY: Diameter calculation completed:', \`2 × \${radius} = \${diameter}\`);
  return diameter;
}

/**
 * Logs the complete geometry calculation results
 */
export async function logGeometryCalculation(
  radius: number,
  area: number, 
  circumference: number,
  diameter: number
): Promise<void> {
  console.log('📊 REAL ACTIVITY: Logging geometry calculation results...');
  
  const logData = {
    timestamp: new Date().toISOString(),
    operation: 'circle_geometry',
    input: { radius },
    results: {
      area: area,
      circumference: circumference,
      diameter: diameter
    },
    formulas: {
      area: 'π × radius²',
      circumference: '2 × π × radius',
      diameter: '2 × radius'
    },
    processingNode: 'temporal-worker-real',
    executionId: Math.random().toString(36).substring(7)
  };
  
  await new Promise(resolve => setTimeout(resolve, 60));
  
  console.log('📝 REAL ACTIVITY: Geometry results logged:', logData);
  console.log('✅ REAL ACTIVITY: Logging completed successfully');
}`;

  const workerCode = `/**
 * Real Temporal Worker for Circle Area Calculation
 */

import { Worker } from '@temporalio/worker';
import * as activities from './activities';

async function runWorker() {
  console.log('🚀 Starting REAL Temporal Worker for Circle Area Calculation...');
  
  try {
    const worker = await Worker.create({
      workflowsPath: require.resolve('./workflows'),
      activities,
      taskQueue: 'circle-area-task-queue',
    });

    console.log('✅ Circle Area Worker created successfully');
    console.log('🔧 Connected to Temporal server: localhost:7233');
    console.log('📋 Task queue: circle-area-task-queue');
    console.log('🔄 Worker ready to process circle geometry workflows...');

    await worker.run();
    
  } catch (error) {
    console.error('❌ Circle Area Worker failed to start:', error);
    console.error('Make sure Temporal server is running on localhost:7233');
    process.exit(1);
  }
}

runWorker().catch(err => {
  console.error('❌ Fatal worker error:', err);
  process.exit(1);
});`;

  const clientCode = `/**
 * Real Temporal Client for Circle Area Calculation
 */

import { Client, Connection } from '@temporalio/client';

async function executeCircleAreaWorkflow() {
  console.log('🚀 Connecting to REAL Temporal Server for Circle Area Calculation...');
  
  try {
    const connection = await Connection.connect({
      address: 'localhost:7233',
    });
    
    const client = new Client({
      connection,
      namespace: 'default',
    });

    console.log('✅ Connected to Temporal server successfully');
    console.log('🌐 Server: localhost:7233');
    console.log('📦 Namespace: default');

    console.log('\\n▶️  Starting REAL circle area workflow execution...');
    
    const workflowId = \`circle-area-\${Date.now()}\`;
    const input = { radius: 5.5 }; // Test with radius of 5.5 units
    
    console.log('🆔 Workflow ID:', workflowId);
    console.log('📥 Input:', input);
    console.log('🌐 Temporal UI: http://localhost:8088/namespaces/default/workflows/' + workflowId);
    
    const handle = await client.workflow.start('${body.name}', {
      args: [input],
      taskQueue: 'circle-area-task-queue',
      workflowId: workflowId,
    });

    console.log('✅ Circle area workflow started successfully!');
    console.log('⏳ Waiting for workflow to complete...');

    const result = await handle.result();
    
    console.log('\\n🎉 Circle area workflow completed successfully!');
    console.log('📊 Complete Results:', result);
    console.log('✅ Success:', result.success);
    console.log('🔢 Radius:', result.input.radius);
    console.log('📐 Area:', result.area, '(π × radius²)');
    console.log('🔄 Circumference:', result.circumference, '(2 × π × radius)');
    console.log('📏 Diameter:', result.diameter, '(2 × radius)');
    console.log('🌐 View in Temporal UI: http://localhost:8088/namespaces/default/workflows/' + workflowId);
    
    connection.close();
    return result;
    
  } catch (error) {
    console.error('❌ Circle area workflow execution failed:', error);
    console.error('Make sure:');
    console.error('  1. Temporal server is running (docker-compose up)');
    console.error('  2. Worker is running (npm run worker)');
    throw error;
  }
}

if (require.main === module) {
  executeCircleAreaWorkflow()
    .then(result => {
      console.log('\\n🏆 Real circle area workflow execution completed successfully!');
      console.log('This proves the workflow automation service works with real Temporal geometry calculations!');
      process.exit(0);
    })
    .catch(error => {
      console.error('Execution failed:', error);
      process.exit(1);
    });
}`;

  const packageJsonCode = `{
  "name": "circle-area-workflow",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "worker": "tsx worker.ts",
    "client": "tsx client.ts",
    "demo": "npm run worker & sleep 3 && npm run client"
  },
  "dependencies": {
    "@temporalio/activity": "^1.12.2",
    "@temporalio/client": "^1.12.2", 
    "@temporalio/worker": "^1.12.2",
    "@temporalio/workflow": "^1.12.2",
    "tsx": "^4.20.4",
    "typescript": "^5.9.2"
  }
}`;

  // Return the generated files
  const response = {
    success: true,
    message: `✅ WORKFLOW AUTOMATION SERVICE: Successfully generated '${body.name}' workflow`,
    workflow: {
      name: body.name,
      description: body.description,
      language: 'typescript',
      framework: 'temporal'
    },
    generatedFiles: {
      'workflows.ts': workflowCode,
      'activities.ts': activitiesCode,
      'worker.ts': workerCode,
      'client.ts': clientCode,
      'package.json': packageJsonCode
    },
    deployment: {
      taskQueue: 'circle-area-task-queue',
      temporalServer: 'localhost:7233',
      temporalUI: 'http://localhost:8088'
    },
    nextSteps: [
      'Deploy generated files to a new directory',
      'Install dependencies with npm install',
      'Start the worker with npm run worker',
      'Execute the workflow with npm run client',
      'View results in Temporal UI'
    ],
    timestamp: new Date().toISOString()
  };

  console.log('✅ WORKFLOW AUTOMATION SERVICE: Response prepared');
  return response;
});

// Start server
const start = async () => {
  try {
    const port = 3002;
    await app.listen({ port, host: '0.0.0.0' });
    console.log(`🚀 Workflow Automation Service running on http://localhost:${port}`);
    console.log(`📡 Health check: http://localhost:${port}/health`);
    console.log(`🔧 Generate endpoint: POST http://localhost:${port}/api/workflows/generate`);
  } catch (err) {
    app.log.error(err);
    process.exit(1);
  }
};

start();